### ISSUE TITLE
Sound cracks when sustain (damper) pedal is on

### ISSUE THREAD

**Issue by postacik** [sinshu/meltysynth#20] opened 2022-05-18 10:36 UTC
Hi,
My midi keyboard application I created with this library runs perfectly.

However sound cracks happen when I play multiple (many many) notes at the same time with the sustain pedal on.

Here is a sample video which describes what I mean:

https://user-images.githubusercontent.com/3977227/169019280-592df62e-19d3-4083-8d55-76dd78f81f52.mp4

I initialize the synthesizer like this:

```csharp
                var format = WaveFormat.CreateIeeeFloatWaveFormat(44100, 2);
                var settings = new SynthesizerSettings(format.SampleRate);
                settings.EnableReverbAndChorus = true;
                synthesizer = new Synthesizer(soundFontPath, settings);
                synthesizer.MasterVolume = 1.5F;
```

And I use the following ISampleProvider with the NAudio library:

```csharp
using System;
using NAudio.Wave;
using MeltySynth;

public class MidiSampleProvider : ISampleProvider
{
    private static WaveFormat format = WaveFormat.CreateIeeeFloatWaveFormat(44100, 2);
    private Synthesizer _synthesizer;

    public MidiSampleProvider(Synthesizer synthesizer)
    {
        _synthesizer = synthesizer;
    }

    public int Read(float[] buffer, int offset, int count)
    {
        _synthesizer.RenderInterleaved(buffer.AsSpan(offset, count));
        return count;
    }
    public WaveFormat WaveFormat => format;
}
```

I have the exact same problem with the Dart version of this library on Android.

Can you please advice what can be done?

**Comment by sinshu** [comment] 2022-05-18 10:46
Does the code below work?
```cs
settings.MaximumPolyphony = 256;
```

**Comment by postacik** [comment] 2022-05-18 11:07
Seems to be working at the start but cracks after a few seconds.

https://user-images.githubusercontent.com/3977227/169024982-f50517f0-b858-4b86-ab2b-b6bfcc738b00.mp4

**Comment by sinshu** [comment] 2022-05-18 11:11
Could you share the sf2 you are using?

**Comment by postacik** [comment] 2022-05-18 11:23
The one I used in the previous video recording was a 500 MB sf2 file.

I tried again with this 16 MB sf2. It cracks with this one too but a bit later.

[p1.zip](https://github.com/sinshu/meltysynth/files/8715730/p1.zip)

https://user-images.githubusercontent.com/3977227/169027563-dc409d0a-9ec2-4dfe-9508-3ac9066ebb2b.mp4

**Comment by sinshu** [comment] 2022-05-18 13:29
High quality SoundFonts often use a sample without loop and entirely flat volume envelope.
If the envelope is entirely flat, MeltySynth cannot well prioritize voices for reuse.

So I improved the prioritization.
If two voices have the same priority, now the older one will be reused.
This is not a perfect solution, but this should improve the sound.

Check this branch:
https://github.com/sinshu/meltysynth/tree/better_prioritization

**Comment by sinshu** [comment] 2022-05-18 15:27
That might be a multi-thread problem.
How did you initialize the NAudio's wave out?

**Comment by postacik** [comment] 2022-05-18 15:44
```csharp
wasapiOut = new WasapiOut(AudioClientShareMode.Shared, 50);
wasapiOut.Init(provider);
wasapiOut.Play();
```

I am using WasapiOut for low latency while playing the midi keyboard...

**Comment by sinshu** [comment] 2022-05-18 15:52
I believe that WasapiOut uses its own thread for audio processing.
So you must do exclusion control between the following things.

1. Rendering waveform
2. Sending notes and CC

Using lock as in the original NAudio example should work.

**Comment by postacik** [comment] 2022-05-18 15:59
> I believe that WasapiOut uses its own thread for audio processing. So you must do exclusion control between the following things.
> 
> 1. Rendering waveform
> 2. Sending notes and CC
> 
> Using lock as in the original NAudio example should work.

I'll have a look at the original NAudio example...

**Comment by postacik** [comment] 2022-05-18 16:00
I could not make Flutter application Windows version crack. Here's a sample:

https://user-images.githubusercontent.com/3977227/169088626-ddb3d52e-a19c-48fb-83bf-899816f9415a.mp4

Now I'll try the Android version...

**Comment by postacik** [comment] 2022-05-18 16:18
Unfortunately the Android version generates heavily distorted sound.

It may be a C# to Dart conversion problem however there is one important point to be considered.

Without the sustain pedal on, there are no problems with the sound.

Can it be because of the CPU power of the Android phone?

The sustain pedal is pressed after the little pause in the video.

https://user-images.githubusercontent.com/3977227/169091846-812ba39f-d172-47ca-b6d0-db184afb6cf8.mp4

**Comment by sinshu** [comment] 2022-05-18 16:25
This sounds CPU power is not enough.
Try setting smaller MaximumPolyphony.
This might increase small cracks due to voice reuse, but it should be better than sound cut off.

**Comment by postacik** [comment] 2022-05-18 16:40
Great tip, now it works.

I had increased MaximumPolyphony to 256 for the tests on Windows.

Now I made it conditional depending on the platform the application is running.

```dart
        ByteData bytes = await rootBundle.load(instrument.path);
        synthesizer = Synthesizer.loadByteData(
          bytes,
          SynthesizerSettings(
            sampleRate: sampleRate,
            blockSize: 64,
            maximumPolyphony: Platform.isWindows ? 256 : 48,
            enableReverbAndChorus: enableReverbAndChorus,
          ),
        );
```

48 worked just fine without any hisses or cracks for the entire test I performed.

Thank you very much.

**Comment by sinshu** [comment] 2022-05-19 11:08
After some tests, I confirmed that the change works as intended, so I merged it to the main branch.
Thank you for reporting the issue.

**Comment by postacik** [comment] 2022-05-19 14:51
Thank YOU for fixing such an edge case in very short time.

**Closed** 2022-05-20 07:59 UTC
